---
- name: Collect Browser Info from Windows Hosts
  hosts: all
  gather_facts: true
  ignore_unreachable: yes

  tasks:
    - name: Get Microsoft Edge version
      win_shell: |
        $paths = @(
          'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe',
          'C:\Program Files\Microsoft\Edge\Application\msedge.exe'
        )
        foreach ($path in $paths) {
          if (Test-Path $path) {
            (Get-Item $path).VersionInfo.ProductVersion
            break
          }
        }
      register: edge_version
      ignore_errors: true
      when: ansible_os_family == 'Windows'

    - name: Get Google Chrome version
      win_shell: |
        $paths = @(
          'C:\Program Files\Google\Chrome\Application\chrome.exe',
          'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
        )
        foreach ($path in $paths) {
          if (Test-Path $path) {
            (Get-Item $path).VersionInfo.ProductVersion
            break
          }
        }
      register: chrome_version
      ignore_errors: true
      when: ansible_os_family == 'Windows'

    - name: Get Mozilla Firefox version
      win_shell: |
        $paths = @(
          'C:\Program Files\Mozilla Firefox\firefox.exe',
          'C:\Program Files (x86)\Mozilla Firefox\firefox.exe'
        )
        foreach ($path in $paths) {
          if (Test-Path $path) {
            (Get-Item $path).VersionInfo.ProductVersion
            break
          }
        }
      register: firefox_version
      ignore_errors: true
      when: ansible_os_family == 'Windows'

    - name: Set browser info line for each host
      set_fact:
        browser_info_line: >-
          {{ ansible_hostname }},
          {{ ansible_host | default(inventory_hostname) }},
          {{ edge_version.stdout | default('Not Found') | trim }},
          {{ chrome_version.stdout | default('Not Found') | trim }},
          {{ firefox_version.stdout | default('Not Found') | trim }}
      when: ansible_os_family == 'Windows'

- name: Combine Browser CSV Report on Controller
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Build browser CSV
      set_fact:
        browser_csv: |
          Hostname,IP,Edge,Chrome,Firefox
          {% for host in groups['all'] %}
          {% if hostvars[host].ansible_os_family == 'Windows' %}
          {{ hostvars[host].browser_info_line | trim }}
          {% endif %}
          {% endfor %}

    - name: Save browser report to CSV file
      copy:
        content: "{{ browser_csv }}"
        dest: "./browser_info_report.csv"

- name: Send Email with Browser Info Report
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Email browser report
      community.general.mail:
        host: 172.25.10.51
        port: 25
        secure: always
        username: m.jahangir.alam@ucb.com.bd
        password: Tasrif@521139
        to: m.jahangir.alam@ucb.com.bd
        subject: "Browser Version Report"
        body: "Attached is the browser version report from all Windows hosts."
        attach:
          - "./browser_info_report.csv"
        secure: always
