---
- name: Get unbound-anchor.timer status on all hosts
  hosts: all
  gather_facts: no
  tasks:

    - name: Check if unbound-anchor.timer is active
      ansible.builtin.command: systemctl is-active unbound-anchor.timer
      register: timer_active
      failed_when: false

    - name: Check if unbound-anchor.timer is enabled
      ansible.builtin.command: systemctl is-enabled unbound-anchor.timer
      register: timer_enabled
      failed_when: false

    - name: Set CSV line for each host
      set_fact:
        timer_info_line: "{{ inventory_hostname }},{{ timer_active.stdout | default('not found') }},{{ timer_enabled.stdout | default('not found on boot') }}"

- name: Combine CSV report on controller
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Build CSV from all hosts
      set_fact:
        csv_report: |
          Host,Active,Enabled
          {% for host in groups['all'] %}
          {{ hostvars[host].timer_info_line | default(host + ',not found,not found on boot') }}
          {% endfor %}

    - name: (Optional) Save CSV to file
      copy:
        content: "{{ csv_report }}"
        dest: "./unbound_timer_report.csv"

    - name: Send CSV report as email attachment
      community.general.mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: m.jahangir.alam@ucb.com.bd
        subject: "Unbound Timer CSV Report"
        body: "Please find attached the unbound-anchor.timer status report in CSV format."
        attach:
          - "./unbound_timer_report.csv"
        secure: always
