---
- name: Check unbound-anchor.timer status
  hosts: all
  gather_facts: no
  tasks:

    - name: Check if unbound-anchor.timer is active
      ansible.builtin.command: systemctl is-active unbound-anchor.timer
      register: timer_active
      failed_when: false

    - name: Check if unbound-anchor.timer is enabled
      ansible.builtin.command: systemctl is-enabled unbound-anchor.timer
      register: timer_enabled
      failed_when: false

    - name: Show unbound-anchor.timer status
      ansible.builtin.debug:
        msg: >
          unbound-anchor.timer is {{ timer_active.stdout | default('not found') }}
          and {{ timer_enabled.stdout | default('not found on boot') }}
