---
- name: Install KB5061087 patch manually
  hosts: all
  gather_facts: no
  tasks:

    - name: Ensure C:\Temp exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Install KB5061087 patch
      win_shell: |
        powershell -Command "Start-Process wusa.exe -ArgumentList 'C:\\Temp\\KB5061087.msu /quiet /norestart' -Wait"
      register: patch_result

    - name: Show full patch result
      debug:
        var: patch_result
