---
- name: Install KB5061087 patch manually
  hosts: all
  gather_facts: no
  tasks:

   - name: Install KB5061087 patch
      win_command: "wusa.exe C:\\Temp\\KB5061087.msu /quiet /norestart"
      register: patch_result

    - name: Show full patch result
      debug:
        var: patch_result
