---
- name: Install KB5061087 patch manually
  hosts: all
  gather_facts: no
  tasks:

    - name: Ensure C:\Temp exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Install KB5061087 patch
      win_shell: wusa.exe C:\Temp\KB5061087.msu /quiet /norestart
      register: patch_result
      ignore_errors: true
