---
- name: Gather OS info
  hosts: all
  gather_facts: true
  tasks:
    - name: Get last Windows Update
      win_shell: |
        Get-HotFix | Sort-Object -Property InstalledOn -Descending | Select-Object -First 1
      register: win_updates
      
    - name: Collect OS info in a fact
      set_fact:
        os_info_report: |
          Host: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          Hostname: {{ ansible_hostname }}
          Last Update: {{ win_updates.stdout }}
          
    - name: Add OS info to central file (delegated to localhost)
      delegate_to: localhost
      run_once: true
      vars:
        reports: "{{ hostvars | dict2items | map(attribute='value.os_info_report') | join('\n\n') }}"
      copy:
        content: "{{ reports }}"
        dest: "./os_info_report.csv"

- name: Send OS info email
  hosts: localhost
  tasks:
    - name: Email report
      community.general.mail:
        host: 103.159.0.237
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: m.jahangir.alam@ucb.com.bd
        subject: "OS Info Report"
        body: "Attached is the full OS information report for all servers."
        attach:
          - "./os_info_report.csv"
