---
- name: Install specific Windows update
  hosts: all
  gather_facts: no
  tasks:
    - name: Install KB5019959 patch
      ansible.windows.win_updates:
        kb_article_ids:
          - KB5019959
        category_names:
          - SecurityUpdates
        reboot: yes
