---
- name: Apply Windows Updates
  hosts: 172.29.10.214
  gather_facts: no
  tasks:
    - name: Install all available updates
      ansible.windows.win_updates:
        kb_article_ids:
          - KB5022906
        reboot: yes
