---
- name: Install KB5058481 patch manually
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure C:\Temp exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Download KB5058481 patch
      win_get_url:
        url: "https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/updt/2025/06/windows10.0-kb5061087-x64_60be6e73e95c9e0cbfb82eb57e5d6088413a6866.msu"
        dest: "C:\\Temp\\KB5061087.msu"

    - name: Install KB5061087 patch
      win_command: wusa.exe C:\\Temp\\KB5061087.msu /quiet /norestart
      register: patch_result
      ignore_errors: true

    - name: Reboot if required
      win_reboot:
        msg: "Restarting after installing KB5058481"
        pre_reboot_delay: 30
      when: patch_result.rc == 3010
