---
- name: Gather OS info
  hosts: all
  gather_facts: true
  tasks:
    - name: Get last Windows Update
      win_shell: |
        (Get-HotFix | Sort-Object -Property InstalledOn -Descending | Select-Object -First 1).InstalledOn
      register: win_update

    - name: Set CSV line
      set_fact:
        os_info_line: os_info_line: "{{ ansible_hostname }},{{ ansible_distribution }} {{ ansible_distribution_version }},{{ ansible_architecture }},{{ inventory_hostname }},{{ win_update.stdout | trim }}"

- name: Combine CSV on controller
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Build CSV from all hosts
      set_fact:
        csv_report: |
          Hostname,OS,Architecture,IP,Last Update
          {% for host in groups['all'] %}
          {{ hostvars[host].os_info_line }}
          {% endfor %}

    - name: Save CSV to file
      copy:
        content: "{{ csv_report }}"
        dest: "./windows_os_report.csv"
        
- name: Send OS info email
  hosts: localhost
  tasks:
    - name: Email report
      community.general.mail:
        host: 103.159.0.237
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: m.jahangir.alam@ucb.com.bd
        subject: "OS Info Report"
        body: "Attached is the full OS information report for all servers."
        attach:
          - "./windows_os_report.csv"
